version: '3'

services:
  proxy:
    # image: nginx:1.23  # this will use the latest version of 1.23.x
    image: uvoo/ntlm-proxy
    # image: nginx:1.11  # this will use the latest version of 1.11.x
    ports:
      - '8000:8000' # expose 8000 on host and sent to 80 in container
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
